# Generated by Django 5.0.3 on 2024-07-27 11:18

import django.contrib.auth.models
import django.db.models.deletion
import sdc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_remove_user_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('house_rent', models.IntegerField()),
                ('house_file', models.FileField(upload_to=sdc.models.document_upload_path)),
                ('fees', models.IntegerField()),
                ('fees_file', models.FileField(upload_to=sdc.models.document_upload_path)),
                ('travelling', models.IntegerField()),
                ('travelling_file', models.FileField(upload_to=sdc.models.document_upload_path)),
                ('bus', models.IntegerField()),
                ('bus_file', models.FileField(upload_to=sdc.models.document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user_images/User/blank.png', upload_to='user_images/')),
                ('city', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('employee_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='sdc.edituser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default='Automatically Update', max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('delievery_addr', models.TextField(max_length=200)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hostel_addr', models.TextField(max_length=200)),
                ('note', models.TextField(max_length=100)),
                ('customer_number', models.CharField(help_text='Customer Mobile Number', max_length=10)),
                ('hotel_number', models.CharField(help_text='Hotel Mobile Number', max_length=10)),
                ('Shop_Location', models.URLField(max_length=100)),
                ('Delievery_Location', models.URLField(max_length=100)),
                ('status', models.TextField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked', 'Picked'), ('delievered', 'Delievered'), ('cancelled_by_admin', 'Cancelled by Admin'), ('cancelled_by_boy', 'Cancelled by Delievery Boy')], default='assigned', max_length=100)),
                ('Current_Location', models.URLField(default='Fetch Automatically', max_length=100)),
                ('distance', models.TextField(default='will be calculated shortly', max_length=10)),
                ('route1', models.URLField(default='Will be updated', max_length=100)),
                ('duration1', models.CharField(default='Update Automatically', max_length=10)),
                ('distance1', models.CharField(default='Update Automatically', max_length=10)),
                ('route2', models.URLField(default='Will be updated', max_length=100)),
                ('duration2', models.CharField(default='Update Automatically', max_length=10)),
                ('distance2', models.CharField(default='Update Automatically', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Assigned_to', models.ForeignKey(limit_choices_to={'is_active': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='sdc.edituser')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_type', models.TextField(choices=[('unicast', 'Send to Perticular One'), ('broadcast', 'Broadcast to all Members')], default='unicast', max_length=60)),
                ('title', models.CharField(default='Message from Admin', max_length=60)),
                ('message', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdc.edituser')),
            ],
        ),
    ]
