# Generated by Django 5.0.3 on 2024-08-01 05:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(default='Tamil', help_text='Language the user knows', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdc.edituser'),
        ),
    ]
