# Generated by Django 5.0.3 on 2024-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc', '0002_order_date_users_age_users_is_online_users_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(default='Tamil', help_text='Language the user knows, Seperate by commas', max_length=200),
        ),
    ]
